services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: candy-cal-be-dev

    restart: unless-stopped

    env_file:
      - /opt/candy-cal-be-dev/.env

    ports:
      - "127.0.0.1:3334:3333"
