services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: candy-cal-be

    restart: unless-stopped

    env_file:
      - /opt/candy-cal-be/.env

    ports:
      - "127.0.0.1:3333:3333"
